services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: darknash
      POSTGRES_PASSWORD: darknash
      POSTGRES_DB: blog
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservice-net
    restart: unless-stopped
volumes:
  postgres:

networks:
  microservice-net:
    driver: bridge