spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  application:
    name: blog-apps


jwt:
  secret: your-256-bit-secret-key-here-make-it-at-least-32-bytes-long

logging:
  level:
    org:
      springframework:
        security:
          web:
            authentication: debug
